on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Inject Commit SHA
        id: get_sha
        run: |
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          mkdir -p dist/assets
          echo $COMMIT_SHA > dist/assets/version
          zip -r dist.zip dist
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "dist.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
