on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Inject Commit SHA
        id: get_sha
        run: |
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo ${{ github.ref }} > dist/assets/version
          zip -r dist.zip dist

      - name: Upload to MinIO
        uses: yakubique/minio-upload@v1.1.3
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_AK }}
          secret_key: ${{ secrets.MINIO_SK }}
          bucket: astrbot-dashboard
          source: ./dist.zip
          # Leading slash is required
          target: '/releases/${{ github.ref_name }}/dist.zip'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: "自动发布"
          artifacts: "dist.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
